### ISSUE TITLE
Create 0.9.3 release?

### ISSUE THREAD

**Issue by oconnedk** [davedevelopment/stiphle#24]
I know there has been no work on this project for a while, but it's probably worth tagging the most recent `master` commits as `0.9.3` as they include some bug fixes.
Most notably, [this change](https://github.com/davedevelopment/stiphle/commit/d152ac5bca66ff32348aaf45e2e45f1fc9173e12) by @villermen fixes an issue with the `DoctrineCache` implementation, which was not providing a default value for the `$sleep` attribute.

Last release was [0.9.2](https://github.com/davedevelopment/stiphle/commits/0.9.2) on 16th Aug, 2017. There have been [a few commits to master](https://github.com/davedevelopment/stiphle/commits/master) since then.

**Comment by davedevelopment** [comment]
Done :+1:

**Comment by oconnedk** [comment]
That's great, thanks a lot!
