### ISSUE TITLE
Cannot be installed on systems with PHP 8

### ISSUE THREAD

**Issue by Vacilando** [davedevelopment/stiphle#25]
0.9.2 required PHP > 5

0.9.3 requires PHP <= 7
Meaning it does not install on systems running PHP 8.

Can this be fixed please.

**Comment by alexthunder3** [comment]
Also interested in this

**Comment by t4keboca** [comment]
if it works, I've created a fork with the composer dependency updated: https://github.com/t4keboca/stiphle

**Comment by davedevelopment** [comment]
Sorry for the delay here, if someone would like to send a PR I'll get it merged.

**Comment by t4keboca** [comment]
Let's give it a try! PR https://github.com/davedevelopment/stiphle/pull/26
Thanks, @davedevelopment for the following up!

**Comment by davedevelopment** [comment]
Done :+1:
