### ISSUE TITLE
Add method to check if limited

### ISSUE THREAD

**Issue by aequasi** [davedevelopment/stiphle#9]
Would be nice, instead of just having a throttle, to check if the key should be throttled, and return true or false if it should be.

**Comment by davedevelopment** [comment]
There is [`getEstimate`](https://github.com/davedevelopment/stiphle/blob/master/src/Stiphle/Throttle/ThrottleInterface.php#L46), I use that for this purpose.

**Comment by aequasi** [comment]
getEstimate doesn't increase the counter though.

**Comment by davedevelopment** [comment]
That was by design, I don't think being refused something should increase the counter?

``` php

$estimate = $throttle->getEstimate('thing', 10, 60000);

if ($estimate > 0) {

    $retry = intval($estimate/1000) + 10;

    header("HTTP/1.1 429 Too Many Requests");
    header("Retry-After: $retry");

    exit;
}

$throttle->throttle('thing', 10, 60000);
```

**Comment by aequasi** [comment]
Yeah, I guess I'm just asking for a shortcut method, that checks, and increments. Instead of needing two methods. Or that PR

**Comment by davedevelopment** [comment]
Would this suffice?

```

function shortcut($throttle, $id, $limit, $milliseconds)
{
    if ($throttle->getEstimate($id, $limit, $milliseconds)) {
        return true;
    }

    $throttle->throttle($id, $limit, $milliseconds);

    return false;
}

**Comment by aequasi** [comment]
should return the wait time, if its throttled, no?

**Comment by davedevelopment** [comment]
> Would be nice, instead of just having a throttle, to check if the key should be throttled, and return true or false if it should be.

I just went with what was said here.
